default_language_version:
    python: python3.10
default_stages: [commit, push]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: black
        name: Run black
        entry: black
        language: system
        types: [python]

    -   id: pylint
        name: Run pylint
        entry: pylint
        language: system
        types: [python]

    -   id: pyright
        name: Run pyright
        entry: pyright
        language: system
        types: [python]
